# Permalinks
permalink:           pretty

# Setup
title:               Natasha S. Borders
tagline:             A nerd's journey into data science
url:                 http://natashaborders.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Natasha S. Borders
  url:               https://twitter.com/natalissaelil
  email:             natasha.s.borders@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/natashaborders

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
